- hosts: localhost
  roles:
    - role: ANXS.oracle-jdk
      oracle_jdk_java_versions: [8]
      oracle_jdk_java_version_default: 8
    - role: JasonGiedymin.sbt
  tasks:
    - user: name=ubuntu uid=1000
    - apt: name=protobuf-compiler update_cache=yes
    - user: name=ubuntu uid=1000 gid=1000
